REST API + new status style
AiRmode/Help pull request #13
Opened 2016-10-16 14:25 UTC by VStankoV

2016-10-16 15:59 UTC, AiRmode requested changes
There are some conflicts, please resolve them first

2016-10-16 15:59 UTC, AiRmode commented on data-model-api/src/main/java/com/provectus/prodobro/actor/company/Company.java
> +    StatusEnumNew getStatus();
Need to remane

2016-10-16 15:59 UTC, AiRmode commented on data-model-api/src/main/java/com/provectus/prodobro/shared/StatusEnumNew.java
> +public enum StatusEnumNew {
Please rename

2016-10-17 06:34 UTC, VStankoV commented
conflicts was resolved by merging and enum was renamed

2016-10-17 06:44 UTC, closed without merging